#!/usr/bin/env bash

while read local_ref local_sha remote_ref remote_sha; do
  if [[ "$remote_ref" =~ ^refs/tags/v ]]; then
    echo "Pushing tag: ${remote_ref}, running pre-tag check..."
    ./scripts/deploy.sh || exit 1
  fi
done

exit 0
